--THIS FUNCTION IS DO 

-- HelloWorld ==========>>>>>  Hello World 
-- NOT COMPLETED


CREATE OR REPLACE FUNCTION F_SPACES_BETWEEN_WORDS (P_TEXT IN VARCHAR2)
    RETURN VARCHAR2
IS
    E_INVALID   EXCEPTION;
    PRAGMA EXCEPTION_INIT (E_INVALID, -01400);
    V_RESULT    VARCHAR2 (100);
BEGIN
    FOR I IN 1 .. LENGTH (P_TEXT)
    LOOP
        BEGIN
            IF SUBSTR (P_TEXT, I, 1) = UPPER (SUBSTR (P_TEXT, I, 1))
            THEN
                V_RESULT :=  REPLACE ( P_TEXT, SUBSTR (P_TEXT, I - 1, 1 ), ' ');
            END IF;
        END;
    END LOOP;

    RETURN V_RESULT;
EXCEPTION
    WHEN E_INVALID
    THEN
        RETURN NULL;
    WHEN OTHERS
    THEN
        RETURN NULL;
END;

-- EXECUTE LEVEL 

BEGIN
    DBMS_OUTPUT.PUT_LINE (F_SPACES ('&P_TEXT'));
END;